register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\AuthController::api

login_check:
    path:     /login_check
    methods:  POST

# get_musteri:
#     path: /get_musteri
#     controller: App\Controller\MusteriController::get_musteri
